title: Granbom
description: Lite av varje om teknik på Svenska
remote_theme: granbom/jekyll-theme-bootstrap4-navbar-cdn

permalink: /:title/
lang: sv
google_analytics:
navbar: dark
navbar-bg: primary
navbar-fixed-top: true
plugins:
  - jekyll-sitemap
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "PG Granbom"
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      author: "PG Granbom"
      layout: "page"
