title: Granbom
description: Lite av varje om teknik på Svenska
markdown: kramdown
remote_theme: granbom/jekyll-theme-bootstrap4-navbar-cdn

permalink: /:title/
lang: sv
google_analytics: UA-106894529-2
plugins:
  - jekyll-sitemap
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      author: PG Granbom
      layout: post